services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=spending;Username=postgres;Password=19006292
