#
#services:
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: expense-api
#    ports:
#      - "5000:8080"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=spending;Username=postgres;Password=19006292
#    depends_on:
#      - db
#
#  db:
#    image: postgres:16
#    container_name: expense-db
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 19006292
#      POSTGRES_DB: spending
#    ports:
#      - "5433:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data
#
#volumes:
#  db_data:


services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=ep-small-bar-aflpa030-pooler.c-2.us-west-2.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=npg_afJ03pjMxtYU;SSL Mode=VerifyFull;Trust Server Certificate=true

